### ISSUE TITLE
Can't start new thread

### ISSUE THREAD

**Issue by careless25** [segmentio/analytics-python#110]
```
Traceback (most recent call last):
File "/var/task/src/utils/lambda_decorators.py", line 47, in handle_internal
return handler_fn(event, context)
File "/var/task/src/utils/lambda_decorators.py", line 30, in handle_internal
return handler_fn(event, context)
File "/var/task/src/handlers/log_analytics.py", line 12, in handle_analytics_identify
analytics_identify(body["uid"], body["cid"], body["identity_info"])
File "/var/task/src/integrations/segment.py", line 12, in analytics_identify
s_client = Client(secrets.segmentWriteKey, debug=False) # segement client object
File "/var/task/analytics/client.py", line 49, in __init__
self.consumer.start()
File "/usr/lib64/python2.7/threading.py", line 739, in start
_start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

Running into this on AWS Lambdas. analytics-python v1.2.8

**Comment by f2prateek** [comment]
Are we allowed to start threads in AWS Lambda?

**Comment by careless25** [comment]
@f2prateek this was working fine until very recently and we have been using this for the past 6 months with AWS lambdas.

**Comment by f2prateek** [comment]
did you upgrade the analytics library version? which version was working before and which version broke?

**Comment by careless25** [comment]
We haven't upgraded. Have always been on v1.2.8. No changes there. Just suddenly (today) we are seeing a spike in errors for analytics.

**Comment by f2prateek** [comment]
Sounds like something maybe changed in the AWS Lambda runtime or possibly in another part of your application in that case?

**Comment by careless25** [comment]
@f2prateek yeah, looking into other sources for the error as well. Thanks for your help. Closing for now
