### ISSUE TITLE
Version 2.3.0 missing jwt as an explicit dependency

### ISSUE THREAD

**Issue by jprafael** [segmentio/analytics-python#427]
The latest version of this package requires JWT to be installed but does not declare it as dependency.

```sh
$ pyenv virtualenv 3.9.17 test
$ pyenv activate test
$ pip install segment-analytics-python@2.3.0
$ python
Python 3.9.17 (main, Jun 30 2023, 11:44:50) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from segment.analytics.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jprafael/.pyenv/versions/test/lib/python3.9/site-packages/segment/analytics/__init__.py", line 3, in <module>
    from segment.analytics.client import Client
  File "/home/jprafael/.pyenv/versions/test/lib/python3.9/site-packages/segment/analytics/client.py", line 9, in <module>
    from segment.analytics.oauth_manager import OauthManager
  File "/home/jprafael/.pyenv/versions/test/lib/python3.9/site-packages/segment/analytics/oauth_manager.py", line 7, in <module>
    import jwt
ModuleNotFoundError: No module named 'jwt'
```

**Comment by XavierGeerinck** [comment]
+1, seeing the same

**Comment by igor-panteleev** [comment]
I faced the same issue.
There was a [similar issue in 2.2.0 ](https://github.com/segmentio/analytics-python/issues/224)

How can errors like those pass tests?

**Comment by MichaelGHSeg** [comment]
That's my fault.  I only added the PyJWT dependency to the requirements.txt that's used for build and testing and missed adding it to setup.py.  I'll get a fix out ASAP and I'm looking into automating a check so we don't miss it in the future.

**Comment by MichaelGHSeg** [comment]
Ok, new release solves the dependency issue.  Apologies.
