### ISSUE TITLE
Weird error while running on AWS Lambda

### ISSUE THREAD

**Issue by mchristen** [segmentio/analytics-python#89]
When trying to flush the event queue I get the following error

```error uploading: [Errno 2] No such file or directory```

I added some print debugging to get the full stacktrace and this is it
```
Traceback (most recent call last):
  File "/var/task/analytics/consumer.py", line 51, in upload
    self.request(batch)
  File "/var/task/analytics/consumer.py", line 87, in request
    self.request(batch, attempt+1)
  File "/var/task/analytics/consumer.py", line 87, in request
    self.request(batch, attempt+1)
  File "/var/task/analytics/consumer.py", line 87, in request
    self.request(batch, attempt+1)
  File "/var/task/analytics/consumer.py", line 87, in request
    self.request(batch, attempt+1)
  File "/var/task/analytics/consumer.py", line 83, in request
    post(self.write_key, batch=batch)
  File "/var/task/analytics/request.py", line 22, in post
    res = _session.post(url, data=data, auth=auth, headers=headers, timeout=15)
  File "/var/task/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/task/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
```

**Comment by f2prateek** [comment]
Is this still an issue? I'm actually a bit surprised given that we use ACM issued certs - so it's weird AWS Lambda wouldn't accept AWS issued certificates.
